### ISSUE TITLE
Request for set difference method

### ISSUE THREAD

**Issue by MareoRaft** [jankapunkt/js-set-extension#1]
**Is your feature request related to a problem? Please describe.**
It seems that the builtin ES6 Set class has no set subtraction.

**Describe the solution you'd like**
Add a `diff` method to the set class.  (I see you have a `symDiff` already, but no `diff`)

**Describe alternatives you've considered**
It would either...
  * take in a single argument and perform the set difference.  For example, `A.diff(B)` returns `A \ B`
  * or take in a list of arguments and subtract all of them from the original set.  `A.diff([B, C])` returns `(A \ B) \ C` or `A \ (B ∪ C)`.

**Additional context**
I can make a PR request for this if you'd like.  Part of this is just me trying to see if you are active on GitHub or not.

**Comment by jankapunkt** [comment]
Thank you for opening this issue.

There is actually the method `Set.complement(a, b)` which subtracts `b` from `a`, like in `A \ B`. It has been taken from this source: https://en.wikipedia.org/wiki/Complement_(set_theory)

The implementation is here: https://jankapunkt.github.io/js-set-extension/index.js.html#line554

It currently takes only two arguments but could theoretically be extended to take arbitrary args. The challenge would be to make this work as part of the static `Set.complement` method instead of being part of an instance of Set.

What do you think?

**Comment by MareoRaft** [comment]
Thanks for the speedy reply!

As a former mathematician, I have always seen the term *complement* used to refer to the *absolute complement* as defined on Wikipedia.  Such an operation would throw an error if there existed an element in B that was not in A, because A is supposed to be the entire universe.

Your implementation is the *relative complement* as defined on Wikipedia, which I have always seen referred to as the *difference*.

So I guess my personal suggestion would be to alter the current function to make it throw an error in that scenario, and then to add a new `diff` method (of an instance) that has the same functionality as the current function.

As for the particular details of whether it should take in one or more arguments, or a single argument that is an iterable, I would probably want whatever seems most appropriate and consistent with the rest of the library.  I think you might know better than me.  In math we use the difference as a binary operation, but I wouldn't be opposed to allowing more arguments if it's a useful convenience.

Thanks again kindly for the reply.

P.S.  The SageMath language might provide some good guidelines for reference:

set difference:
https://doc.sagemath.org/html/en/reference/sets/sage/sets/set.html#sage.sets.set.Set_object.difference

set (absolute) complement:
doesn't exist

**Comment by jankapunkt** [comment]
Hi sorry for the delay, I just came back here and realized, that I didn't answer and I wonder why...

So regarding your proposed change, I am fine with it. If you like to create a PR please also add / update the tests.

The sagemath.org reference could also act as a guideline / goal for (re-)designing the API as I think that API's should follow the domain's rules and conventions.

If you are short on time I can also update the package, based on your proposed changes.

**Comment by jankapunkt** [comment]
Merged by #3 Feel free to reopen if there are still issues related to this issue.
