### ISSUE TITLE
differences

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/js-set-extension#10]
There needs to be a boolean operation on instances of Sets that allow the following:

What you say: "The set difference of A and B"
What you type: `Set.difference(A, B)`
note: no change

What you say: "A minus B"
What you type: `A.minus(B)`
description: This is the same as the difference operator, but with a different syntax.

What you say: "The symmetric difference of M"
What you type: `Set.symmetricDifference(M)`
ref: https://en.wikipedia.org/wiki/Symmetric_difference#n-ary_symmetric_difference
description: The repeated symmetric difference, as described in ref above.
note: This function *should* be able to take in an iterable of length 0 or 1.
  * `Set.symmetricDifference([A])` should output A.
  * `Set.symmetricDifference([])` should output the empty set.

What you say: "The symmetric difference of A and B"
What you type: `A.symmetricDifference(B)`
ref: https://en.wikipedia.org/wiki/Symmetric_difference
description: A triangle B.

**Comment by MareoRaft** [comment]
branch matt/differences

**Comment by MareoRaft** [comment]
merged into 2.x.x
