### ISSUE TITLE
products

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/js-set-extension#11]
There needs to be a boolean operation on instances of Sets that allow the following:

What you say: "The cartesian product of M"
What you type: `Set.cartesianProduct(M)`
description: Perform the n-ary cartesian product (aka the n-fold cartesian product) of all the sets in X
example:
  * `Set.cartesianProduct([A, B, C])` should output the set whose elements anything of the form (a, b, c) where a is in A, b is in B, and c is in C.
note: Note that `A.cartesianProduct(B).cartesianProduct(C)` is NOT the same as `Set.cartesianProduct([A, B, C])`.

What you say: "The cartesian product of A and B"
What you type: `A.cartesianProduct(B)`
ref: https://en.wikipedia.org/wiki/Cartesian_product
description: the binary operation version.

**Comment by MareoRaft** [comment]
branch matt/products

**Comment by MareoRaft** [comment]
merged into 2.x.x
