### ISSUE TITLE
more meta tags so people can find repo

### ISSUE THREAD

**Issue by MareoRaft** [jankapunkt/js-set-extension#19]
Is it possible to add more meta tags to the GitHub repo?  Currently we have

  * javascript
  * set
  * set-theory
  * math

I think we should also add

  * union
  * intersection
  * difference
  * subset

and even more, if GitHub allows it.

As for the **NPM** listing, currently we have

  * set
  * math
  * superset
  * subset
  * union
  * intersection
  * complement
  * symmetric difference
  * powerset

to which we could add

  * difference
  * set theory
  * proper subset
  * proper superset

.  The reason behind all of this is simply to help people to find our repo when they are searching for it.  I'm hoping we can increase visibility of this repo and ultimately get more people to use it.

**Comment by jankapunkt** [comment]
I added all the listed but missing tags to the GitHub repo. For the NPM tags I will create a new PR

**Comment by MareoRaft** [comment]
Thanks!!

GitHub tags added to repo and package.json changes merged into master.

@jankapunkt need to republish to npm for changes to take affect there, then can close issue.

**Comment by MareoRaft** [comment]
Ok to close this.  Newer version will get published to npm sooner or later anyway.
