### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by MareoRaft** [jankapunkt/js-set-extension#21]
I'm not sure how you want to deal with all these breaking changes (due to name changes of some of the functions).

I might suggest that we start a new branch (called "version2" or similar) and make our PR's to that branch instead.  In a month or so when all of our desired changes are done, you may choose to "release" version 2 to the master branch.  Breaking changes usually warrant an increment of the major version number.

To make the transition easier, you can make the old function names aliases to the new function names, for backwards compatibility.  That could be accompanied with a warning and deprecation message.  Whatever you prefer.

For now I will continue making my PR's to the master branch, until you let me know otherwise.

**Comment by jankapunkt** [comment]
>I might suggest that we start a new branch (called "version2" or similar) and make our PR's to that branch instead. In a month or so when all of our desired changes are done, you may choose to "release" version 2 to the master branch

That would require to PR into another branch than `master`.

> Breaking changes usually warrant an increment of the major version number.

Agree. Would be then 2.x.x

> To make the transition easier, you can make the old function names aliases to the new function names, for backwards compatibility. That could be accompanied with a warning and deprecation message. Whatever you prefer.

It would be a good practice but I think there aren't so many package users right now that this would have a bigger impact. Maybe just displaying a warning / info message if someone installs 2.x.x on the console would be sufficient?

**Comment by MareoRaft** [comment]
Okay, I think I want to move forward with making a "version2" branch then.  That way I don't need to worry about disrupting users so much.  I will assume you are okay with this unless I hear otherwise.

> Maybe just displaying a warning / info message if someone installs 2.x.x on the console would be sufficient?

Yes, I think that would be sufficient.

In addition, when a user calls `isProperSubsetOf`, for example, they will get an error message that says "`isProperSubsetOf has been changed to isProperSubset.  Please use that function instead`".

**Comment by MareoRaft** [comment]
See `2.x.x` branch

**Comment by jankapunkt** [comment]
BTW I think you don't have to close the PRs but just re-adjust the destination branch in the PR from master to `version2`

**Comment by jankapunkt** [comment]
Okay I just saw you added the changes already to the `2.x.x` branch, which is okay but I would go for per-feature-PRs in the future, so we can still review with a more narrow set of files/features to discuss.

**Comment by MareoRaft** [comment]
btw, this repo just became helpful for something i was doing at work, wohoo!

**Comment by MareoRaft** [comment]
@jankapunkt  Is there anything left to be done before releasing version 2?  I would like to wrap up v2 if possible.  I think a lot of the tickets about adding new functions/features can be put on hold until after the release of v2.

**Comment by jankapunkt** [comment]
I just opened a PR for merging v2 into master. We need to resolve all other PRs first an can then finally merge
