### ISSUE TITLE
suggested function list

### ISSUE THREAD

**Issue by MareoRaft** [jankapunkt/js-set-extension#24]
i'm going to explain this soon, but i need to jot something down real quick.  you can ignore this for now

list in progress

    isProperSubset --> isStrictSubset, properSubset, strictSubset

**Comment by MareoRaft** [comment]
If a user types a wrong but reasonable guess for a function name, I would like to emit an error that tells them what the CORRECT function name is.

For example, if a user types `A.empty()`, I would like to throw the error "The function 'empty' is invalid.  Please use 'isEmpty' instead.".

Following is a list of function names and corresponding incorrect names that are nonetheless reasonable.

    add --> append, push, insert
    has --> contains
    toArray --> array
    any --> anElement (or other way around)
    randomElement --> rand, random, randElement
    isEmpty --> empty
    isSuperset --> superset, isSupersetOf, supersetOf
    isSubset --> subset, isSubsetOf, subsetOf
    isProperSuperset --> properSuperset, isProperSupersetOf, properSupersetOf, isStrictSuperset, strictSuperset, isStrictSupersetOf, strictSupersetOf
    isProperSubset --> properSubset, isProperSubsetOf, properSubsetOf, isStrictSubset, strictSubset, isStrictSubsetOf, strictSubsetOf
    equals --> equal, isEqualTo
    copy --> clone
    intersection --> intersect (and vice-versa, depending on whether it's a method or not)
    difference --> minus (and vice-versa, ditto)
    complement --> compliment
    symmetricDifference --> symDiff, symDifference, symmetricDiff
    cartesianProduct --> prod, product, cartProd, cartProduct, cartesianProd
    powerSet --> powerset, subsets (because "powerset" is sometimes used as a single word)

**Comment by MareoRaft** [comment]
going to create branch `matt/2.x.x/suggest` to try this out

**Comment by MareoRaft** [comment]
This is meant to make debugging easier for users.  This will also help people to migrate from version 1 to version 2 when the time comes.

**Comment by jankapunkt** [comment]
I think it is good to keep this as long as there will be a transition to v2.x.x from 1.x.x but it should be removed after a while (for instance a year or so).

After that people should be highly encouraged to read or very extensive and detailed documentation :-)

I added the respective comments to the #31 PR so we leave a reminder in the code for ourselves when there is a "cleanup" in the future.

**Comment by MareoRaft** [comment]
I had intended on keeping it long-term, but I would totally be okay with eventually removing it if you prefer.  Please see my comment on the PR for a use-case of when it would be useful.

This "suggested function feature" is similar to what `git` does when you type an invalid subcommand.  For example,

    ~/programming/js-set-extension % git pussh
    git: 'pussh' is not a git command. See 'git --help'.
    
    The most similar command is
            push

Git is even smarter though.  It uses some fuzzy spell-checking algorithm to find the closest subcommand.  The one downside to this "suggested function feature" is that if somebody programmatically looks at the keys defined on the `Set` object, it will include all of the invalid keys we added.  These could potentially get included in some fancy auto-complete text-editor, etc.

Let me know what you decide, I will be happy to go either way.

**Comment by jankapunkt** [comment]
I like the idea, I just want to make sure we keep the overall package size small enough to keep the package attractive. Let's keep it for now and see how much the package will grow overall.

**Comment by jankapunkt** [comment]
Implemented in #31 feel free to reopen if there is anything to discuss related to this issue.
