### ISSUE TITLE
isEmpty method

### ISSUE THREAD

**Issue by MareoRaft** [jankapunkt/js-set-extension#26]
Create an isEmpty boolean method for Set.

isEmpty --> tells you if it's an empty set or not (has a size of 0)

`A.isEmpty()`

something like

    () => this.size === 0

**Comment by MareoRaft** [comment]
branch `matt/isEmpty`

**Comment by jankapunkt** [comment]
You can also create PR to master from this branch as it is not breaking things.

**Comment by MareoRaft** [comment]
new branch to be merged w/ master: `matt/master/isEmpty`

**Comment by MareoRaft** [comment]
TODO: still need to throw an error if an arg is given
