### ISSUE TITLE
create randomElement method

### ISSUE THREAD

**Issue by MareoRaft** [jankapunkt/js-set-extension#27]
create randomElement boolean method for Set

Returns an element from the set, at random, with a uniform distribution.

something like

    () => Math.floor(Math.random() *  this.size)

**Comment by MareoRaft** [comment]
@jankapunkt Do you want this feature to go into master branch or 2.x.x?

**Comment by jankapunkt** [comment]
I would merge it into master as it is already a benefit to the current API and doesn't break things.

**Comment by MareoRaft** [comment]
branch `matt/master/randomElement`
