### ISSUE TITLE
better whitespace in docs

### ISSUE THREAD

**Issue by MareoRaft** [jankapunkt/js-set-extension#32]
It's weird in the docs how the "example" section has an abnormally large amount of whitespace above it, and the title for a new function has almost no whitespace above it.

It makes it look like the "example" belongs to the function below it, when this is not the case.

Current doc image:

![Screenshot 2019-04-13 22 42 33](https://user-images.githubusercontent.com/860303/56087670-7f1af580-5e3d-11e9-9676-3ea676647710.png)

As you can see "(static) complement..." has almost no whitespace above it, but it should have a large amount of whitespace.

I want to play around with the CSS file a bit and make the docs more readable.

**Comment by jankapunkt** [comment]
That would be great. I just use jsDoc out of the box and did not take the time for configuration yet.
There are even themes and plugins out there. Just check the http://usejsdoc.org/ pages.,

**Comment by MareoRaft** [comment]
A few I liked...

docdash:
https://cancerberosgx.github.io/jsdoc-templates-demo/demo/docdash/Environment.html

braintree:
https://cancerberosgx.github.io/jsdoc-templates-demo/demo/braintree-jsdoc-template/Environment.html

pixi:
https://cancerberosgx.github.io/jsdoc-templates-demo/demo/pixi-jsdoc-template/Environment.html

docstrap:
https://github.com/docstrap/docstrap

See https://github.com/cancerberoSgx/jsdoc-templates-demo/blob/master/generate.sh for help in installing them...


I'm going to try out braintree and then modify the CSS to change the colors and spacing a bit.  I also like docdash...

**Comment by MareoRaft** [comment]
branches:
matt/master/braintree
matt/master/docdash

**Comment by MareoRaft** [comment]
<img width="1440" alt="Screenshot 2019-04-20 18 21 35" src="https://user-images.githubusercontent.com/860303/56462924-37deb880-6399-11e9-8ce5-b791acb6d47a.png">

**Comment by MareoRaft** [comment]
<img width="1440" alt="Screenshot 2019-04-20 18 21 44" src="https://user-images.githubusercontent.com/860303/56462935-580e7780-6399-11e9-8df6-8e6ed2a3ed87.png">

**Comment by MareoRaft** [comment]
So basically what I can say is that I think braintree is prettier, but docdash is actually better for people trying to find the information they need.

Braintree puts the Wikipedia link in a more hidden spot.  Docdash puts it up front.  Docdash also puts the method names in big color swatches which makes it easier visually to see when a new method begins, which basically fixes the issue I was complaining about.  Docdash also puts the Example block closer to the beginning, which i think is good because most people just want to see an example.

So I'm leaning towards docdash right now.

**Comment by jankapunkt** [comment]
Hi, sorry for not responding. Had some crunch time on a project recently plus holidays etc. I also agree for docdash as it has a clear layout and I like the example boxes a lot.

**Comment by jankapunkt** [comment]
@MareoRaft is it possible to merge this already into the current master?

**Comment by MareoRaft** [comment]
No worries.  So I customized docdash a bit to make it closer to the actual lodash stuff.  I hope you like it.  Let me know.  Opening a PR to merge this into master.

**Comment by jankapunkt** [comment]
merged in #35
