### ISSUE TITLE
Split into modules as file will soon exceed 1000 lines

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/js-set-extension#33]
It makes sense to split the code into seperate files (aka modules). However, we need first to complete the the missing enhancements and then analyze the code structure to determine, where it makes sense to move code into own files and where not.

**Comment by MareoRaft** [comment]
Splitting this file up is a good idea, but I don't think it needs to be done for 2.0.0, since it makes no difference to the user.

**Comment by jankapunkt** [comment]
Yes we can keep this open for later. For now we should be still good to go.

**Comment by MareoRaft** [comment]
Here would be my suggestion for breaking down index.js into separate files:

### utils.js

Helper functions / variables that never get attached to Set or Set.prototype:

  * suggest
  * checkRules
  * checkSet
  * checkSets
  * checkArgsSingle
  * arbitraryToBinary
  * correctSetNameToIncorrectNames
  * correctSetPrototypeNameToIncorrectNames
  * setSuggestions

The remaining code could be broken down into an arbitrary.js file where you define the overrides on Set and then a binary.js file where you define the overrides on Set.prototype.
