### ISSUE TITLE
suggested Set implementation for JS 5

### ISSUE THREAD

**Issue by MareoRaft** [jankapunkt/js-set-extension#36]
If I'm using JS 5 but I want the JS 6 style [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) class, is there a recommended way / library for including that class into my JS 5 project?

I'm running into a situation where I really want the set datatype at work, but we are stuck with a JavaScript engine that only runs JS 5.  I was wondering if you happened to know.  Ideally, such a Set class would:

  * be as close to the JS 6 Set class as possible
  * could be extended with `js-set-extension`

**Comment by jankapunkt** [comment]
There should be always a transpiled version in the `dist` folder, for example here: https://github.com/jankapunkt/js-set-extension/blob/master/package/dist/index.js

If you need a custom branch or even a custom commit to be es5 compatible you can run locally `npm run build-full` inside the package folder and check the `dist` folder afterwards.

Does that help?

**Comment by MareoRaft** [comment]
That's helpful, but I also need a Set class in the first place.

This library is only an extension, and it needs a Set class to extend.  Something along the lines of [node-set](https://github.com/pvorb/node-set) or [set.js](https://github.com/gkatsev/set.js).  I just don't know to what extent those are similar to es6's Set.

**Comment by MareoRaft** [comment]
I think

    import Set from 'core-js-pure/features/set';

is what I'm looking for, although I haven't had time to test it out yet.  See [core-js](https://www.npmjs.com/package/core-js) project.

**Comment by MareoRaft** [comment]
Yes, one of these options should do the trick for your situation.  Need to test a bit more before confirming

    // if you want to polyfill `Set`:
    // all `Set`-related features, with ES proposals:
    import 'core-js/features/set';

    // stable required for `Set` ES features and features from web standards
    // (DOM collections iterator in this case):
    import 'core-js/stable/set';

    // only stable ES features required for `Set`:
    import 'core-js/es/set';

    // the same without global namespace pollution:
    import Set from 'core-js-pure/features/set';
    import Set from 'core-js-pure/stable/set';
    import Set from 'core-js-pure/es/set';
