### ISSUE TITLE
Why can we use global variable?

### ISSUE THREAD

**Issue by Eracal** [jankapunkt/js-set-extension#39]
I am writing a similar extension and I found this project. It's an awesome project.  But I can't figure out why can use `global` variable directly? 

Maybe the purpose is that package can be used in browser and nodejs.

But why and what make it works. Is it `babel` or `core.js`? Can you share some info about that?

Thank you:)

**Comment by jankapunkt** [comment]
The `global` variable is only used in the dev-code. For creating the `dist` we use babel 7 and it should create ECMA5 compatible code, running in major Browsers and on Node. Do you experience any errors?

**Comment by Eracal** [comment]
Without having experienced error. Just for learning.
I also write a similar set-extension. For the purpose of cross-platform,  I thought it was `globalThis`, `global` variable can work is beyond my expectation. Get it.
P.S. I push an optimization of intersection. It seems something wrong in the Travis CI build.

**Comment by jankapunkt** [comment]
@Eracal the builds are running again so we can review the PR :-)
