### ISSUE TITLE
Update CI Environment

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/js-set-extension#40]
We can't merge, because the Node environment fails on our CI. Needs top be fixed soon!

// cc @MareoRaft sorry for the longer break, I will check on that soon and then we can continue to merge and improve to v2

**Comment by MareoRaft** [comment]
I'm seeing the error

    /home/travis/build/jankapunkt/js-set-extension/package/node_modules/requizzle/lib/requizzle.js:45
    	if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
    	               ^
    TypeError: Cannot read property '0' of null

in our CI test.  It looks like the issue has already been resolved in May:

https://github.com/hegemonic/requizzle/issues/6

So I think that updating to the latest version of JSDoc should fix the issue.

**Comment by MareoRaft** [comment]
Updating JSDoc seems to have worked.  See PR #42

**Comment by jankapunkt** [comment]
Thank oyu @MareoRaft all fixed an running again via #42
