### ISSUE TITLE
Replace global with globalThis for browser

### ISSUE THREAD

**Issue by prajaybasu** [jankapunkt/js-set-extension#52]
The polyfill currently assumes `global` will be defined, which is not the case when using Vite or other ESM/esbuild based bundlers.
I would like to be able to use the polyfill out of the box without defining global before my scripts run.

For example: https://github.com/stardazed/sd-streams/blob/master/packages/streams-polyfill/src/sd-streams-polyfill.ts

**Comment by jankapunkt** [comment]
Hi @prajaybasu thank you for the issue. Would you like to provide a PR, based on the suggested example from the link? I would review and merge. Don't care about updating dependencies, I will take care of it after merging. What do you think?

**Comment by jankapunkt** [comment]
@prajaybasu I released 1.5.0 which should fix this issue

**Comment by jankapunkt** [comment]
Feel free to reopen if the issue persists
