### ISSUE TITLE
Equality

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/js-set-extension#7]
There needs to be a boolean operation on instances of Sets that allow the following:

What you say: "if A is equal to B, ..." or "if A equals B, ..."
What you type: if (A.equals(B)) {

**Comment by MareoRaft** [comment]
I'll branch off master for this one, since it doesn't involve the other stuff

branch

matt/equals

**Comment by MareoRaft** [comment]
@jankapunkt Should I be updating the docs in each branch as I go by running npm run docs?  I'm sortof afraid that I'm going to run into merge conflicts.  Also it clutters the diff.  For now I am updating the docs.

**Comment by jankapunkt** [comment]
It's okay, the diff clutter is not that big of an issue since I can fold the output. When there are merge conflicts you can jump back to an older commit, which is why it is good to run the docs at the very end.

Anyway, I will always run the docs again when publishing the merged master to the NPM registry. We can then still figure out what to do. If it gets too messy we may drop it. But for now I think it is good also for you to see, if the documentation is sufficient.

**Comment by MareoRaft** [comment]
merged into 2.x.x
