### ISSUE TITLE
Union

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/js-set-extension#8]
What you say: "The union of M"
What you type: `Set.union(M)`
ref: https://en.wikipedia.org/wiki/Union_(set_theory)#Arbitrary_unions
description: The arbitary union operator acts on any iterable (of sets) M and returns a single set whose elements consist of the elements of each set in the iterable.
note: Throws an error if you don't give it exactly 1 argument
note: Throws an error if the input is not an iterable of sets
note: The above two notes will be referred to as (*), to avoid repetition below.

What you say: "The union of A and B" or "A union B"
What you type: `A.union(B)`
ref: https://en.wikipedia.org/wiki/Union_(set_theory)#Union_of_two_sets
description: The small union operator is a binary operator which takes in two sets.
note: (*)
note: the function should be able to take in an iterable of length 0 or 1.
  * `Set.union([A])` should output A.
  * `Set.union([])` should output the empty set.

**Comment by MareoRaft** [comment]
Let me start with this ticket since union is very straight-forward.

**Comment by MareoRaft** [comment]
branch matt/union

https://github.com/jankapunkt/js-set-extension/tree/matt/union

**Comment by jankapunkt** [comment]
Fixed via #13
