### ISSUE TITLE
intersections

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/js-set-extension#9]
There needs to be a boolean operation on instances of Sets that allow the following:

What you say: "The intersection of M"
What you type: `Set.intersection(M)`
ref: https://en.wikipedia.org/wiki/Intersection_(set_theory)#Arbitrary_intersections
description: The arbitrary intersection operator acts on any iterable (of sets) and returns a single set whose elements consist of the elements that occur in every single set in the iterable.
note: (*)
note: the function should be able to take in an iterable of length 0 or 1.
  * `Set.intersection([A])` should output A.
  * `Set.intersection([])` should output the entire universe (but we don't have a global "universe" right now, so for now we should throw an error).

What you say: "The intersection of A and B" or "A intersect B"
What you type: `A.intersect(B)`
ref: https://en.wikipedia.org/wiki/Intersection_(set_theory)#Definition
description: The small intersection operator is a binary operator which takes in two sets.

**Comment by MareoRaft** [comment]
branch matt/intersection

**Comment by jankapunkt** [comment]
fixed via #15
